import { Oswald, Plus_Jakarta_Sans } from "next/font/google";
import "../globals.css";
import Navbar from "../components/ui/Navbar";
import Footer from "../components/ui/Footer";
import { Toaster } from "react-hot-toast";
import NextAuthProvider from "../Providors/NextAuthProvider";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Eco Plates",
    template: "%s | Eco Plates",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${plusJakartaSans.variable} ${oswald.variable} antialiased`}
      >
        <NextAuthProvider>
          <Navbar />
          {children}
          <Toaster />
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  );
}
